Add TAG leadership election governance template
cncf/toc pull request #1195
Opened 2023-10-23 17:03 UTC by leonardpahlke

This PR adds a template under the `toc/tags/resources/tag-formation-template` to document the leadership election process within TAGs. This PR https://github.com/cncf/toc/pull/1086 established the `/tags/resources` structure, and this PR adds content to one of the empty stub files. More PRs will follow to add content to the other template files (like: https://github.com/cncf/toc/pull/1128 and https://github.com/cncf/toc/pull/1116).

The election process is a combined version of the [TAG ENV TL](https://github.com/cncf/tag-env-sustainability/blob/main/governance/tech-lead-proposal-process.md), [TAG ENV Chair](https://github.com/cncf/tag-env-sustainability/blob/main/governance/chair-proposal-process.md) and [TAG ENV WG Chair](https://github.com/cncf/tag-env-sustainability/blob/main/governance/working-group-chair-proposal-process.md) election process. TAG ENV originally pulled the governance files from TAG Security, see [file](https://github.com/cncf/tag-security/blob/main/governance/tech-lead-proposal-process.md).

2023-10-24 14:19 UTC, TheFoxAtWork requested changes
Overall looks good, made some suggestions to increase clarity.

2023-10-24 14:19 UTC, TheFoxAtWork commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +* Justification
```suggestion
* Justification
* Nominee Biography
```

2023-10-24 14:19 UTC, TheFoxAtWork commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +The TAG leadership will release aggregate information about the nominees at the end of the nomination process. Aggregate information will not include who nominated someone.
```suggestion
The TAG leadership will release aggregate information about the nominees at the end of the nomination process. Aggregate information will not include who nominated someone.

## Next Steps

If the role under nomination requires TOC approval or vote, the TAG Co-chairs are responsible for coordinating and executing that in accordance with the TOC's processes (defined previously).
```

2023-10-24 18:11 UTC, leonardpahlke commented
ref "Implementation of an updated TAG formation process" issue: https://github.com/cncf/toc/issues/1043#event-10606256466

2023-10-31 20:29 UTC, leonardpahlke commented
I am thinking about splitting the document into two parts.

1. election procedure for TAG chairs and TAG TLs
2. election procedure for working group and project leads.

I think the procedure for working group and project leads can be simplified.

2023-10-31 20:38 UTC, TheFoxAtWork commented
@leonardpahlke, agreed. Since working group and project leads are a different process, than TAG Chairs and TAG TLs it makes sense to separate them.

2023-10-31 20:39 UTC, TheFoxAtWork approved these changes

2024-08-30 14:27 UTC, TheFoxAtWork commented
@nikhita @linsun would you both PTAL and see if this aligns with the current direction of the leadership terms and ladder effort? if it does would you provide your review so this may be merged in?

2024-10-01 15:29 UTC, linsun commented
Sorry about the delay with lots of travel, I will review this this week and make sure the doc content is also merged in: https://docs.google.com/document/d/1xP1SXy4LW9yxI_1cs3GYQyv6wb3-JYBdXE8MYO0RnqQ/edit?usp=sharing

2024-10-07 01:57 UTC, linsun commented
Hi @leonardpahlke this looks great. Based on our prior discussion, do you think we can add the following as well?

**Leadership Terms:**
Each leadership role is on a 2 year term once appointed.

**Elections:**
Elections should be conducted by CNCF staff. TAG leadership Election should start 1-2 months after the TOC election finishes each year, pending CNCF staff’s availability to run the elections. 

For the immediate election in 2025, roughly 50% of the roles should be made available for election where existing leaders can choose to rerun, starting with the longest serving leaders. The rest of the leads who are not up for election should plan to be up for elections in 2026.

Co-chairs can be nominated by any existing co-chairs or TOC member. TL roles should be nominated by any existing co-chairs or TLs. WG leads can be nominated by any TAG leaders.TAGs may define their own process by which they field nominations for these roles, provided they adhere to CNCF and TOC expectations of openness, transparency, and accountability.

Co-chair elections should be voted on by the TOC. Other TAG leads elections should be voted by TAG co-chairs, TLs, WG leads or other active members of the TAG.

**Vacancies**
In the event that a TAG lead vacates their seat during their term, a by-election shall be conducted to fill the position for the remainder of the term in accordance with the regular election procedure.
The TAG co-chairs may initiate a vote of no confidence in a TAG leader when the TAG leader has not performed any TAG leader tasks for 6 months. The leader shall be removed if the motion is approved by at least sixty percent (60%) of the TAG leaders along with the approval support from all of the TOC Liaisons for the TAG.

**Liaisons**
Following the TOC liaison for TAG model, we recommend that at least one TAG co-chair or/and TL serve as liaison for each TAG WG so the co-chair or/and TL can help resolve any concerns from the WG within the TAG’s own governance. This ensures TAG Leadership remains aware and conscious of the WG’s activities, deliverables, and overall health.

2024-10-07 14:13 UTC, JustinCappos commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +* Be the author of at least one pull request against the `<TAG NAME>` repository
A quick question:  What is the purpose of calling this out versus making it part of the list below?   It seems to already be somewhat related to the commenting on PRs, etc. issue below.

Is the author of a PR the person who created it?   Is any person who did a lot of the work on it an author?   What about someone who reviewed and commented heavily on it?   Do all PRs regardless of length / purpose / complexity count the same here?   

I know this is all subjective and I'm not proposing to define all the corner cases.   I'd actually prefer to make this less specific and less emphasized.   My concern is that I don't want someone with imposter syndrome who has been a great contributor, but who didn't create a PR to feel like their application shouldn't be put forth.

2024-11-05 12:39 UTC, leonardpahlke commented
Thanks for the input. Will make updates to the PR this week.

2024-11-19 16:31 UTC, TheFoxAtWork commented
@leonardpahlke any update on this?

2024-11-21 09:43 UTC, leonardpahlke commented
Updated the PR. @linsun please take a look. 

> Liaisons
> Following the TOC liaison for TAG model, we recommend that at least one TAG co-chair or/and TL serve as liaison for each TAG WG so the co-chair or/and TL can help resolve any concerns from the WG within the TAG’s own governance. This ensures TAG Leadership remains aware and conscious of the WG’s activities, deliverables, and overall health.

I am wondering if this would be better placed in the roles document, since It's not really about the election, right?

2024-12-02 22:50 UTC, linsun commented
Thanks @leonardpahlke! will review it shortly!

2024-12-03 03:07 UTC, linsun commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +co-chairs can be nominated by any existing co-chairs or TOC member. TL roles should be nominated by any existing co-chairs or TLs. WG leads can be nominated by any TAG leaders. TAGs may define their
```suggestion
Co-chairs can be nominated by any existing co-chairs or TOC member. TL roles should be nominated by any existing co-chairs or TLs. WG leads can be nominated by any TAG leaders. TAGs may define their own process by which they field nominations for these roles, provided they adhere to CNCF and TOC expectations of openness, transparency, and accountability.
```

2024-12-03 03:08 UTC, linsun commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +  * ominations: Open for 1-2 months. Co-chairs or TOC members can nominate.
```suggestion
  * nominations: Open for 1-2 months. Co-chairs or TOC members can nominate.
```

2024-12-03 03:09 UTC, linsun commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +  * nominations: Open for 1-2 months. Co-chairs or TOC members can nominate.
```suggestion
  * Nominations: Open for 1-2 months. Co-chairs or TOC members can nominate.
```

2024-12-03 03:13 UTC, linsun commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +* Come from someone other than the nominee
I'd in favor of self nominate if co-chair wants to continue to serve.

2024-12-03 03:14 UTC, linsun commented on tags/resources/tag-formation-templates/template-leadership-election-process.md
> +* Come from someone other than the nominee
```suggestion
```

2024-12-03 03:15 UTC, linsun approved these changes
LGTM

corrected a few typos and removed one of the nomination requirements to allow self nomination which we allow for TOC candidates as well.

2024-12-03 03:15 UTC, merged