[Proposal] - Meshery to incubation
cncf/toc pull request #1264
Opened 2024-03-01 22:02 UTC by sandramsc

Since joining the CNCF Sandbox in June 2021, Meshery has experienced remarkable growth and development, showcased by its extensive feature set and vibrant community engagement 🚀. 

With this momentum, we're thrilled to announce our intention to move Meshery to the next stage of incubation within the CNCF. 

 🌟 Thank you! 🌟

2024-03-01 22:18 UTC, jameshorton2337 commented on proposals/incubation/meshery.md
> +* Accumulated a total of 4,000 new GitHub stars
```suggestion
* Accumulated a total of 5,000 new GitHub stars
```
+1,000

2024-03-02 13:44 UTC, ritiksaxena124 requested changes

2024-03-02 13:44 UTC, ritiksaxena124 commented on proposals/incubation/meshery.md
> +Meshery's [security reporting process](https://docs.meshery.io/project/security-vulnerabilities) is well-documented and has [previous and current CVEs](https://docs.meshery.io/project/security-vulner
```suggestion
Meshery's [security reporting process](https://docs.meshery.io/project/security-vulnerabilities) is well-documented and has [previous and current CVEs](https://docs.meshery.io/project/security-vulnerabilities) published along with the reporting process and expectation setting of how reports are handled. This process is followed successfully with GitHub engineers being the most recent to report vulnerabilities and a Meshery maintainer (from Intel) to provide patches. Maintainers strive to acknowledge reports within 24 hours of being received and offer an analysis and plan for a full response within 10 days.
```

2024-04-15 01:35 UTC, gyohuangxin commented on proposals/incubation/meshery.md
> +Meshery boasts a diverse and active community of maintainers, with [15 maintainers](https://github.com/meshery/meshery/blob/main/MAINTAINERS.md) overseeing the ~30 repositories included in the `meshe
```suggestion
Meshery boasts a diverse and active community of maintainers, with [15 maintainers](https://github.com/meshery/meshery/blob/master/MAINTAINERS.md) overseeing the ~30 repositories included in the `meshery` GitHub organization.  and [extension modules](https://github.com/meshery/meshery/blob/main/EXTENSIONS.md). 
```
And the link https://github.com/meshery/meshery/blob/main/EXTENSIONS.md can't be opened either.

2024-04-29 22:31 UTC, 864893031735973 approved these changes

2024-05-29 04:30 UTC, Bneill67 approved these changes

2024-07-09 14:51 UTC, angellk commented
@sandramsc and Meshery maintainers, we (the TOC) have reworked the process(es) a bit - please review the latest in:
https://github.com/cncf/toc/blob/main/process/README.md#applying-to-become-an-incubating-or-graduating-project

There's a slightly longer form/issue to fill in:
https://github.com/cncf/toc/blob/main/process/README.md#applications-to-move-levels-are-done-by-submitting-an-incubation-or-graduation-application-issue-on-the-toc-repo

Please re-open the application issue with the new process and link to this issue.

2024-08-01 20:24 UTC, angellk commented
thank you @sandramsc ! replaced by #1386

2024-08-01 20:24 UTC, closed without merging

2024-08-05 22:20 UTC, leecalcote commented
Meshery's incubation proposal is scheduled for presentation in TAG Runtime's August 15th meeting.

2024-08-05 23:11 UTC, craigbox commented
> Meshery's incubation proposal is scheduled for presentation in TAG Runtime's August 15th meeting.

https://github.com/cncf/toc/issues/1386#issuecomment-2266644260