Update TAG app delivery personell
cncf/toc pull request #1305
Opened 2024-04-18 14:04 UTC by lianmakesthings

- Alois stepped down as Chair
- Lian was voted in as Chair and confirmed by TOC
- Alex Jones stepped down as Tech Lead
- updated some other information in various places where they were missed
@Riaankl

2024-04-18 18:05 UTC, Riaankl commented
@lianmakesthings I would propose inline with the new TAG Charter template that I shared the TAG App delivery to remove the leadership information from the charter, instead of updating it.

/CC @thschue

2024-04-19 18:38 UTC, angellk requested changes
Please add Alois to Technical Leads

2024-04-22 12:22 UTC, Riaankl commented
> @lianmakesthings I would propose inline with the new TAG Charter template that I shared the TAG App delivery to remove the leadership information from the charter, instead of updating it.
> 
> /CC @thschue

@angellk do you agree that the  leadership should be removed from the charter in line with the new template?

2024-05-10 19:25 UTC, TheFoxAtWork approved these changes

2024-05-11 06:23 UTC, kevin-wangzefeng commented
+1 to  "the leadership should be removed from the charter".
But I don't think it's a blocking issue of this PR, as there are other TAG charters content leadership info already, we  can fix them with a cleanup PR after the new TAG Charter template ready.

2024-05-13 13:19 UTC, merged

2024-05-13 13:21 UTC, riaankleinhans commented
@kevin-wangzefeng I agree and merged. Thanks

The Charter & README Temples is ready and can found [here](https://docs.google.com/document/d/1ut60KmkIwggpnF0Wtb8-qoECnB9W0qq8nihqKxYQ_a0/edit#heading=h.4zf0p5wp9r8t)