Update DEFINITION.md
cncf/toc pull request #543
Opened 2020-09-25 10:24 UTC by volaka

Added Turkish (Türkçe) language

2021-08-14 14:27 UTC, OrlinVasilev commented on DEFINITION.md
> +**Cloud Native Computing Foundation**, açık kaynaklı, satıcı-bağımsız (vendor-neutral) projelerden oluşan bir ekosistemi teşvik ederek ve sürdürerek bu paradigmanın benimsenmesini sağlamayı amaçlamak
last sentence must be : "Bu yenilikleri herkesin erişebilirsi için son teknoloji paternlerini demokratikleştiriyoruz."

2021-08-14 14:28 UTC, OrlinVasilev requested changes
last sentence must be : "Bu yenilikleri herkesin erişebilirsi için son teknoloji paternlerini demokratikleştiriyoruz."

2021-08-16 05:27 UTC, OrlinVasilev commented
@volaka ^^ :)

2021-12-14 17:18 UTC, amye commented
@volaka: can you accept changes? We're doing an end of year github cleanup, and I'd hate to close this if it's still relevant.

2021-12-14 17:29 UTC, volaka commented
Hi, sorry I didn't see the request. I have changed it with better grammar. The requested change from @OrlinVasilev is not understandable. ("erişilebilirsi" is not a word :) )

2022-03-22 17:20 UTC, caniszczyk commented
resubmit and deal with conflicts, sorry we let this one go stale :/

2022-03-22 17:20 UTC, closed without merging