Update DEFINITION.md
cncf/toc pull request #989
Opened 2023-01-02 14:09 UTC by TaniaFedirko

Signed-off-by: Tania Fedirko <66258087+TaniaFedirko@users.noreply.github.com>
Add Ukrainian Definition

2023-01-02 14:10 UTC, TaniaFedirko commented
Add Ukrainian Definition

2023-03-21 04:39 UTC, craigbox commented
Spot check with Google Translate LGTM.  
Adding a couple of potential reviewers: @idvoretskyi @kivashch to get this moving.

2023-03-21 08:53 UTC, idvoretskyi requested changes

2023-03-21 08:53 UTC, idvoretskyi commented on DEFINITION.md
> +Фундація хмарних нативних обчислень прагне сприяти впровадженню цієї парадигми шляхом розвитку і підтримки екосистеми проектів з відкритим вихідним кодом, незалежних від постачальників. Ми демократиз
s/постачальників/вендорів/

2023-03-21 08:53 UTC, idvoretskyi commented on DEFINITION.md
> +Ці методи дозволяють створювати слабко пов'язані системи, які є стійкими, керованими і спостережуваними. У поєднанні з надійною автоматизацією вони дозволяють інженерам часто і передбачувано вносити
> слабко пов'язані системи

Please rephrase.

2023-03-21 08:53 UTC, idvoretskyi commented on DEFINITION.md
> +Нативні хмарні технології дозволяють організаціям створювати та запускати масштабовані додатки в сучасних динамічних середовищах, таких як публічні, приватні та гібридні хмари. Контейнери, сервісні с
> сервісні сітки

I believe, Service Meshes are meant here, I'd look for a better translation of the definition.

2023-08-17 18:32 UTC, TheFoxAtWork commented
I would love for this to be merged in but there are some conflicts and outstanding comments that need resolved, @TaniaFedirko our apologies on the delay, would you update the PR?

2023-10-10 15:21 UTC, TheFoxAtWork commented
@TaniaFedirko & @idvoretskyi  would you take a look?

2023-10-11 07:01 UTC, idvoretskyi commented
Ping @TaniaFedirko :)

2024-04-16 17:54 UTC, TheFoxAtWork commented
Closing this PR - internationalism of the definition will need refreshed with the New Definition to be merged. 
CC @jeefy

2024-04-16 17:54 UTC, closed without merging